build_from:
  amd64: "ghcr.io/home-assistant/amd64-base-python:3.12-alpine3.19"
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:3.12-alpine3.19"
labels:
  org.opencontainers.image.title: "Home Assistant MCP Server"
  org.opencontainers.image.source: "https://github.com/roandegraaf/ha-mcp"
